# Generated by Django 3.1 on 2020-09-05 02:10

from django.db import migrations, models
import jobsearch.models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsearch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactData',
            fields=[
                ('identifier', models.TextField(db_column='Id', primary_key=True, serialize=False, unique=True)),
                ('company_name', models.TextField(blank=True, db_column='company_name', max_length=70, null=True)),
                ('contact_name', models.TextField(blank=True, db_column='contact_name', max_length=70, null=True)),
                ('contact_type', models.TextField(db_column='contact_type')),
                ('date', models.DateTimeField(blank=True, db_column='contact_date', null=True)),
                ('comments', models.TextField(blank=True, db_column='comments', null=True)),
                ('inserted_date', models.DateTimeField(blank=True, db_column='inserted_date', null=True)),
            ],
            options={
                'db_table': 'contacts',
                'managed': False,
            },
            bases=(models.Model, jobsearch.models.Printable),
        ),
        migrations.CreateModel(
            name='TemporaryId',
            fields=[
                ('id', models.TextField(db_column='ID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Temporary_Ids',
                'managed': False,
            },
        ),
    ]
